<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \Coinpaprika\Client();


$crypto_ids = ["btc-bitcoin", "sol-solana", "eth-ethereum", "doge-dogecoin", "dot-polkadot"];

// var_dump($client->getCoins());


var_dump($client->getTickerByCoinId("btc-bitcoin"));
